
insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34546', 'CLIENTNOTE', 'ATESH1', '4/3/2015', '1', 'RÜZGAR GÜLÜ DEFARMASYON ZAMANSIZ ARIZASI.', 'YARIMCA', 'YARORG', 'ATESH1', '4/3/2015', 'TR3977720', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34065', 'CLIENTNOTE', 'ATESH1', '8/13/2014', '1', 'DUMAN DEDEKTÖRLERI HAVA SARTLARI SEBEBIYLE HATA VERMESI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '8/13/2014', 'TR3495823', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34245', 'CLIENTNOTE', 'ATESH1', '11/4/2014', '1', 'ORTAK HÜCRE KARBONDIOKSIT SÖNDÜRME SISTEMI FAULT UYARI VERMESI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '11/4/2014', 'TR3675458', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34345', 'CLIENTNOTE', 'ATESH1', '1/1/2015', '1', 'GAZ DEDEKTÖRLERI PANOSU KART -POWER SUPLEY SES YAPMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '1/1/2015', 'TR3786205', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34646', 'CLIENTNOTE', 'ATESH1', '5/4/2015', '1', 'PIKNIK ACIL STOP ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '5/4/2015', 'TR4038374', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33825', 'CLIENTNOTE', 'ATESH1', '2/17/2014', '1', 'ARITMA KUM FILTRESI VE AKTIF KARBON DEGISIMI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '2/17/2014', 'TR3101299', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33885', 'CLIENTNOTE', 'ATESH1', '4/9/2014', '1', 'YOL TARAFI AYDINLATMA DIREGI LAMBA YANMAMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '4/9/2014', 'TR3209618', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33925', 'CLIENTNOTE', 'ATESH1', '4/22/2014', '1', 'T200 GAZ FAZI  VANASI  AKTÜATÖRÜ AÇMA KAPAMA ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '4/22/2014', 'TR3190259', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34326', 'CLIENTNOTE', 'ATESH1', '12/20/2014', '1', 'AYDINLATMA DIREGI LAMBA YANMAMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '12/20/2014', 'TR3733331', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34365', 'CLIENTNOTE', 'ATESH1', '1/22/2015', '1', '24 LÜK KARUSEL VARYATÖR TERMIK VE KONDAKTÖR ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '1/22/2015', 'TR3817846', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34626', 'CLIENTNOTE', 'ATESH1', '4/30/2015', '1', 'ÇUKUROVA JENEROTORU ISITICI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '4/30/2015', 'TR4038393', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33705', 'CLIENTNOTE', 'ATESH1', '1/30/2014', '1', 'GÜVENLIK TUR SAATI 2  NOLU KURMA NOKTASI OKUMAMA ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '1/30/2014', 'TR3039861', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33725', 'CLIENTNOTE', 'ATESH1', '1/30/2014', '1', 'SÖFÖR BEKLEME ODASI KLIMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '1/30/2014', 'TR3064810', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34085', 'CLIENTNOTE', 'ATESH1', '8/23/2014', '1', 'TANK 100 MANUEL MEKANIK SEVIYE CIHAZI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '8/23/2014', 'TR3413607', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34105', 'CLIENTNOTE', 'ATESH1', '8/23/2014', '1', 'TANK 100 SICAKLIK TRANSMETERI BILGI PLC YE GITMEMESI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '8/23/2014', 'TR3495796', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34225', 'CLIENTNOTE', 'ATESH1', '10/15/2014', '1', 'KARTLI KAPI GEÇIS SISTEMI KABLO DEFARMASYON OLMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '10/15/2014', 'TR3625316', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34265', 'CLIENTNOTE', 'ATESH1', '11/9/2014', '1', 'SUNDURMA 24 LÜK VE 42 LIK ÇATI EMNIYET HALATLARININ DEFARMASYON ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '11/9/2014', 'TR3691219', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33865', 'CLIENTNOTE', 'ATESH1', '3/24/2014', '1', 'SIGINAK HAVALANDIRMA FANI ÇALISMAMA ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '3/24/2014', 'TR3101281', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33985', 'CLIENTNOTE', 'ATESH1', '5/26/2014', '1', '42 LIK SUNDURMA BOYAHANE BANTI TAHRIK GURUBU VE RULMAN DEGISIMI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '5/26/2014', 'TR3298846', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34025', 'CLIENTNOTE', 'ATESH1', '7/15/2014', '1', '42 LIK SUNDURMA EX PRIZ SASE YAPMASI SIGORTA ATTIRMASI ZAMANSIZA ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '7/15/2014', 'TR3175424', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34045', 'CLIENTNOTE', 'ATESH1', '8/10/2014', '1', '1 NOLU DOM KAMERA EKRAN KARARMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '8/10/2014', 'TR3419849', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34205', 'CLIENTNOTE', 'AKYUS', '8/29/2014', '1', 'GIRIS KAPISI ELEKTRIK MOT. ARIZASI', 'YARIMCA', 'YARORG', 'AKYUS', '8/29/2014', 'TR3537670', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34466', 'CLIENTNOTE', 'ATESH1', '2/11/2015', '1', 'ACIL ÇIKIS KAPISI RAY TEKERI RULMAN ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '2/11/2015', 'TR3853449', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34486', 'CLIENTNOTE', 'ATESH1', '2/12/2015', '1', 'ALÇAK GERILIM ODASI SEBEKE ENERJI VAR IKAZ LAMBASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '2/12/2015', 'TR3872187', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34606', 'CLIENTNOTE', 'ATESH1', '4/28/2015', '1', 'BUHAR JENEROTORÜ ZAMANSIZ ARIZA', 'YARIMCA', 'YARORG', 'ATESH1', '4/28/2015', 'TR3895775', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33685', 'CLIENTNOTE', 'ATESH1', '1/27/2014', '1', '42 LIK KARUSEL AOV VANASI KAPATMAMA ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '1/27/2014', 'TR3039873', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33965', 'CLIENTNOTE', 'ATESH1', '4/30/2014', '1', 'SANAYI DOLUM SUNDURMASI EX ARMATÜR CAM KIRILARAK AÇILMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '4/30/2014', 'TR3240871', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34305', 'CLIENTNOTE', 'ATESH1', '12/9/2014', '1', 'BUHAR JENARATÖR GAZ HORTUMU DEFARMASYON ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '12/9/2014', 'TR3733349', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34325', 'CLIENTNOTE', 'ATESH1', '12/20/2014', '1', 'PAROTONER DIREGI VE IDARI BINA LEDLI AYDINLATMA LAMBASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '12/20/2014', 'TR3733340', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34506', 'CLIENTNOTE', 'ATESH1', '3/9/2015', '1', 'TANK 100 ELEKTRONIK SEVIYE  CIHAZI EKRAN GÖSTERGESI ZAMANSIZ ARIZASI.', 'YARIMCA', 'YARORG', 'ATESH1', '3/9/2015', 'TR3940518', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34566', 'CLIENTNOTE', 'ATESH1', '4/9/2015', '1', 'T100 AOV 105 VANASININ SIVIÇ AYARLAMA VE MEKANIK ÇALISMA', 'YARIMCA', 'YARORG', 'ATESH1', '4/9/2015', 'TR3999663', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34567', 'CLIENTNOTE', 'ATESH1', '4/9/2015', '1', 'NULL', 'YARIMCA', 'YARORG', 'ATESH1', '4/9/2015', 'TR3999663', 'WORKORDER', 'TR', '0')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34647', 'CLIENTNOTE', 'ATESH1', '5/4/2015', '1', 'TAKNK 300 ÜST VANALAR AÇMA KAPAMA BUTONU LAMBA ARZASI', 'YARIMCA', 'YARORG', 'ATESH1', '5/4/2015', 'TR3993387', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33805', 'CLIENTNOTE', 'ATESH1', '2/17/2014', '1', 'ARITMA ARIZALARI,AKTIF KARBON VE KUM FILTRE TANKI ZAMANSIZARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '2/17/2014', 'TR3101290', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33845', 'CLIENTNOTE', 'ATESH1', '2/25/2014', '1', 'TRAFO ÜNITESI SLIKAJEL DEGISIMI ,YAG KAÇAGI VE KONDANSATÖR DEGISIMI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '2/25/2014', 'TR3101308', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34125', 'CLIENTNOTE', 'ATESH1', '8/23/2014', '1', 'TANK 200 SVIYE CIHAZI PLC PANOYA BILGI GÖNDERMEMESI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '8/23/2014', 'TR3495805', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34165', 'CLIENTNOTE', 'AKYUS', '8/29/2014', '0', 'GIRIS KAPISI ELEKTRIK MOTORU ARIZA', 'YARIMCA', 'YARORG', 'AKYUS', '8/29/2014', 'TR3537670', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34185', 'CLIENTNOTE', 'AKYUS', '8/29/2014', '0', 'NULL', 'YARIMCA', 'YARORG', 'AKYUS', '8/29/2014', 'TR3537670', 'WORKORDER', 'TR', '0')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34586', 'CLIENTNOTE', 'ATESH1', '4/20/2015', '1', 'GAZ DEDEKTÖRÜ PANELI KORNA SES AZ ÇIKMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '4/20/2015', 'TR3940527', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34666', 'CLIENTNOTE', 'ATESH1', '6/17/2015', '1', 'GÜVENLIK CCTV MONITÖR KAPANMASI VE PANOLARIN BÖLGE OLARAK KOPUKLUK OLMASI ZAMANSIZ ARIZASI.', 'YARIMCA', 'YARORG', 'ATESH1', '6/17/2015', 'TR4027238', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('33765', 'CLIENTNOTE', 'ATESH1', '1/30/2014', '1', 'SÖFÖR BEKLEME ODASI KLIMASI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '1/30/2014', 'TR3064828', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34285', 'CLIENTNOTE', 'ATESH1', '12/3/2014', '1', 'SUNDURMA 24 LÜK VE 42 LIK ÇATI EMNIYET HALATLARININ DEFARMASYON ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '12/3/2014', 'TR3691219', 'WORKORDER', 'TR', '1')

insert into worklog ( WORKLOGID, LOGTYPE, CREATEBY, CREATEDATE, CLIENTVIEWABLE, DESCRIPTION, SITEID, ORGID, MODIFYBY, MODIFYDATE, RECORDKEY, CLASS, LANGCODE, HASLD ) VALUES ('34527', 'CLIENTNOTE', 'ATESH1', '3/18/2015', '1', 'DUMAN DEDEKTÖRÜ 6. BÖLGE FAULT VERMESI ZAMANSIZ ARIZASI', 'YARIMCA', 'YARORG', 'ATESH1', '3/18/2015', 'TR3885908', 'WORKORDER', 'TR', '1')

